bind 0.0.0.0
port 26379
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor app-redis app-redis-primary 6379 2
sentinel down-after-milliseconds app-redis 5000
sentinel failover-timeout app-redis 10000
sentinel parallel-syncs app-redis 1
