sonar.projectKey=tituslhy_fictional-bassoon
sonar.organization=tituslhy
sonar.python.version=3.13
# sonar.sources=backend,frontend
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**,**/docker/**,**/*.xml,**/*.yaml
sonar.tests=backend,frontend
sonar.test.inclusions=**/test/**,**/tests/**,**/*.test.ts,**/*.spec.ts,**/*_test.py
