[tox]
envlist = py313
minversion = 4.0
skipsdist = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest
    ruff
    mypy
commands =
    ruff check {posargs:.}
    mypy {posargs:.}
    pytest {posargs:-v}

[tool:pytest]
testpaths = tests

[mypy]
python_version = 3.13
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
