global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'celery_worker'
    static_configs:
      - targets: ['celery_worker:8001']

  - job_name: 'citus'
    static_configs:
      - targets: ['citus_coordinator_exporter:9187', 'citus_worker_1_exporter:9187', 'citus_worker_2_exporter:9187']

  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer_exporter:9127']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'app_redis_ha'
    static_configs:
      - targets:
          - 'app-redis-primary-exporter:9121'
          - 'app-redis-replica-1-exporter:9121'
          - 'app-redis-replica-2-exporter:9121'

  - job_name: 'app_redis_sentinel'
    static_configs:
      - targets:
          - 'app-redis-sentinel-1-exporter:9121'
          - 'app-redis-sentinel-2-exporter:9121'
          - 'app-redis-sentinel-3-exporter:9121'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-01:9363', 'clickhouse-02:9363', 'clickhouse-03:9363']

  - job_name: 'minio_cluster'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio1:9000']

  - job_name: 'minio_node'
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets: ['minio1:9000', 'minio2:9000', 'minio3:9000', 'minio4:9000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
