{
 "title": "MinIO Dashboard",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Offline Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_offline_total",
     "legendFormat": "Offline Drives"
    }
   ]
  },
  {
   "title": "Online Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_online_total",
     "legendFormat": "Online Drives"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_cluster_capacity_raw_free_bytes",
     "legendFormat": "Free Capacity"
    },
    {
     "expr": "minio_cluster_capacity_raw_total_bytes",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Node Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "minio_node_drive_used_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}