{
 "title": "Redis HA",
 "tags": [
  "redis",
  "ha"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Redis HA Target Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"app_redis_ha|app_redis_sentinel\"}",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Connected Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_slaves{job=\"app_redis_ha\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"app_redis_ha\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{job=~\"app_redis_ha|app_redis_sentinel\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=~\"app_redis_ha|app_redis_sentinel\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}